apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tilleggsstonader-integrasjoner
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "250M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"

spec:
  port: 8080
  image: {{ image }}
  ingresses:
    - https://tilleggsstonader-integrasjoner.intern.dev.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
      cpu: 500m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "3611981f-eda7-46ab-b8f2-50c3159e101c" # 0000-GA-Tilleggsstonader-Veileder
          - id: "31a99292-9461-40bf-b2d0-a815697dfbb4" # 0000-GA-tilleggsstonader-integrasjonersbehandler
          - id: "dab3f549-f5f0-4a9c-9f5b-1f6a15ae8424" # 0000-GA-Tilleggsstonader-Beslutter
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
  accessPolicy:
    inbound:
      rules:
        - application: tilleggsstonader-sak
        - application: tilleggsstonader-soknad-api
        - application: tilleggsstonader-klage
    outbound:
      rules:
        - application: api-intern
          namespace: aap
        - application: familie-ef-sak
          namespace: teamfamilie
        - application: etterlatte-samordning-vedtak
          namespace: etterlatte
      external:
        - host: saf-q2.dev-fss-pub.nais.io
        - host: oppgave.dev-fss-pub.nais.io
        - host: arena-api-q1.dev-fss-pub.nais.io
        - host: dokdistfordeling.dev-fss-pub.nais.io

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev

