CLIENT_ENV: dev

clients:
  arena:
    uri: https://arena-api-q1.dev-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamarenanais.arena-api-q1/.default
  oppgave:
    uri: https://oppgave-q1.dev-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.oppgavehandtering.oppgave-q1/.default
  dokarkiv:
    uri: https://dokarkiv.dev-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.dokarkiv-q1/.default
  dokdist:
    uri: https://dokdistfordeling-q1.dev-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.saf-q1/.default
  saf:
    # saf-q1.dev er på saf.dev
    uri: https://saf.dev-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.saf-q1/.default