CLIENT_ENV: dev

clients:
  oppgave:
    uri: https://oppgave-q1.dev-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.oppgavehandtering.oppgave-q1/.default
  dokarkiv:
    uri: https://dokarkiv.dev-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.dokarkiv-q1/.default
  dokdist:
    uri: https://dokdistfordeling-q1.dev-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.dokdistfordeling/.default