application:
  name: tilleggsstonader-integrasjoner

server:
  servlet:
    context-path: /
  port: 8080

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  prometheus.metrics.export.enabled: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token
  client.registration:
    oppgave:
      resource-url: ${clients.oppgave.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.oppgave.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    oppgave-client_credentials:
      resource-url: ${clients.oppgave.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.oppgave.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

CLIENT_ENV: prod

clients:
  oppgave:
    uri: https://oppgave.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-gcp.oppgavehandtering.oppgave/.default
