application:
  name: tilleggsstonader-integrasjoner

CLIENT_ENV: prod

server:
  servlet:
    context-path: /
  port: 8080

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  prometheus.metrics.export.enabled: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
  client.registration:
    oppgave:
      resource-url: ${clients.oppgave.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.oppgave.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    oppgave-client_credentials:
      resource-url: ${clients.oppgave.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.oppgave.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    dokarkiv:
      resource-url: ${clients.dokarkiv.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.dokarkiv.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    dokarkiv-client_credentials:
      resource-url: ${clients.dokarkiv.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.dokarkiv.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    dokdist:
      resource-url: ${clients.dokdist.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.dokdist.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    dokdist-client_credentials:
      resource-url: ${clients.dokdist.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.dokdist.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    saf:
      resource-url: ${clients.saf.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.saf.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    saf-client_credentials:
      resource-url: ${clients.saf.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.saf.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    arena-client_credentials:
      resource-url: ${clients.arena.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.arena.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    aap-client_credentials:
      resource-url: ${clients.aap.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.aap.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    enslig-client_credentials:
      resource-url: ${clients.enslig.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.enslig.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    etterlatte-client_credentials:
      resource-url: ${clients.etterlatte.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.etterlatte.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    azure-graph-credentials:
     resource-url: ${clients.azure-graph.uri}
     token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
     grant-type: client_credentials
     scope: ${clients.azure-graph.scope}
     authentication:
       client-id: ${AZURE_APP_CLIENT_ID}
       client-secret: ${AZURE_APP_CLIENT_SECRET}
       client-auth-method: client_secret_basic

    aad-graph-onbehalfof:
      resource-url: ${AAD_GRAPH_API_URI}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${AAD_GRAPH_SCOPE}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    aad-graph:
      resource-url: ${AAD_GRAPH_API_URI}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${AAD_GRAPH_SCOPE}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

clients:
  arena:
    uri: https://arena-api.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamarenanais.arena-api/.default
  oppgave:
    uri: https://oppgave.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.oppgavehandtering.oppgave/.default
  dokarkiv:
    uri: https://dokarkiv.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.dokarkiv/.default
  dokdist:
    uri: https://dokdistfordeling.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.saf/.default
  saf:
    uri: https://saf.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.saf/.default
  aap:
    uri: http://api-intern.aap
    scope: api://${CLIENT_ENV}-gcp.aap.api-intern/.default
  enslig:
    uri: http://familie-ef-sak.teamfamilie
    scope: api://${CLIENT_ENV}-gcp.teamfamilie.familie-ef-sak/.default
  etterlatte:
    uri: http://etterlatte-samordning-vedtak.etterlatte
    scope: api://${CLIENT_ENV}-gcp.etterlatte.etterlatte-samordning-vedtak/.default
  azure-graph:
    uri: https://graph.microsoft.com/v1.0/
    scope: https://graph.microsoft.com/.default
