application:
  name: tilleggsstonader-integrasjoner

CLIENT_ENV: prod

server:
  servlet:
    context-path: /
  port: 8080

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
      security:
        protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: PKCS12
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
    producer:
      acks: all
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer


management:
  endpoint.health.show-details: always
  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
    path-mapping:
      info: "status/isAlive"
  prometheus.metrics.export.enabled: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token
  client.registration:
    oppgave:
      resource-url: ${clients.oppgave.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.oppgave.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    oppgave-client_credentials:
      resource-url: ${clients.oppgave.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.oppgave.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    dokarkiv:
      resource-url: ${clients.dokarkiv.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.dokarkiv.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    dokarkiv-client_credentials:
      resource-url: ${clients.dokarkiv.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.dokarkiv.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    dokdist:
      resource-url: ${clients.dokdist.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.dokdist.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    dokdist-client_credentials:
      resource-url: ${clients.dokdist.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.dokdist.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic

    saf:
      resource-url: ${clients.saf.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
      scope: ${clients.saf.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic
    saf-client_credentials:
      resource-url: ${clients.saf.uri}
      token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
      grant-type: client_credentials
      scope: ${clients.saf.scope}
      authentication:
        client-id: ${AZURE_APP_CLIENT_ID}
        client-secret: ${AZURE_APP_CLIENT_SECRET}
        client-auth-method: client_secret_basic



clients:
  oppgave:
    uri: https://oppgave.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.oppgave/.default
  dokarkiv:
    uri: https://dokarkiv.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.dokarkiv/.default
  dokdist:
    uri: https://dokdistfordeling.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.saf/.default
  saf:
    uri: https://saf.prod-fss-pub.nais.io
    scope: api://${CLIENT_ENV}-fss.teamdokumenthandtering.saf/.default
